global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "batch_job_monitor"
    scrape_interval: 5s
    static_configs:
      - targets: ["batch-job-monitor:8000"]
        labels:
          service: "batch_jobs"

  # Add more job scrapers as needed
  # - job_name: "node_exporter"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]